# NumPy Excercises

In [81]:
import numpy as np
print(np.__version__)

1.21.5


# Array Creation


## Create a numpy array of size 10, filled with zeros.

In [82]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create a numpy array with values ranging from 10 to 49

In [83]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Create a numpy matrix of 2*2 integers, filled with ones.

In [84]:
np.ones([2,2], dtype = np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

# Create a numpy matrix of 3*2 float numbers, filled with ones.

In [85]:
np.ones([3,2], dtype= np.float32)

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

# 

# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [86]:
X = np.arange(4, dtype= np.int8)
np.ones_like(X)

array([1, 1, 1, 1], dtype=int8)

# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [87]:
X = np.array([[1,2,3],[5,6,7]], dtype = np.int8)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

# Create a numpy matrix of 4*4 integers, filled with fives.

In [88]:
np.ones([4,4], dtype=np.int8)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [89]:
X = np.array([[2,3],[6,2]], dtype= np.int8)
X
np.ones_like(X)*7

array([[7, 7],
       [7, 7]], dtype=int8)

# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [90]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a numpy array, filled with 3 random integer values between 1 and 10.

In [91]:
np.random.randint(10, size=3)

array([6, 5, 4])

# Create a 3 * 3 * 3 numpy matrix, filled with random float values.

In [92]:
np.random.rand(3,3,3)

array([[[0.11247355, 0.4431618 , 0.94265101],
        [0.70797436, 0.14213809, 0.86958509],
        [0.81346943, 0.12770183, 0.05294392]],

       [[0.30996866, 0.78765963, 0.48741858],
        [0.90938151, 0.88249913, 0.33671811],
        [0.52148574, 0.82479964, 0.53530553]],

       [[0.90970703, 0.15811713, 0.11672999],
        [0.71839293, 0.45178969, 0.37092172],
        [0.7271189 , 0.15179043, 0.77902679]]])

# Given the X python list convert it to an Y numpy array

In [93]:
X = [2, 7, 9]
print(X, type(X))
Y = np.array(X)
print(Y, type(Y))

[2, 7, 9] <class 'list'>
[2 7 9] <class 'numpy.ndarray'>


# Given the X numpy array, make a copy and store it on Y.

In [94]:
X = np.array([2, 3], dtype=np.int8)
print(X, id(X))
Y = np.copy(X)
print(Y, id(Y))

[2 3] 2213466198832
[2 3] 2213466201616


# Create a numpy array with numbers from 1 to 10

In [95]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Create a numpy array with the odd numbers between 1 to 10

In [96]:
np.arange(1,11, 2)

array([1, 3, 5, 7, 9])

# Create a numpy array with numbers from 1 to 10, in descending order.

In [97]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8


In [98]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Show the memory size of the given Z numpy matrix

In [99]:
Z  = np.zeros((10,10))
print('%d bytes' % (Z.size * Z.itemsize))

800 bytes


# Array indexation

## Given the X numpy array, show it's second element

In [100]:
X = np.arange(9)
X[1]

1

# Given the X numpy array, show it's last element

In [104]:
X = np.arange(3, 10)
X[-1]

9

# Given the X numpy array, show it's first three elements

In [107]:
X = np.arange(2,10)
print(X)
X[0:3]

[2 3 4 5 6 7 8 9]


array([2, 3, 4])

# Given the X numpy array, show all middle elements

In [109]:
X = np.arange(10)
print(X)
X[1:-1]

[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8])

# Given the X numpy array, show the elements in an odd position

In [112]:
X = np.arange(1, 10)
print(X)
X[::2]

[1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

# Given the X numpy matrix, show the first row elements

In [114]:
X = np.arange(9).reshape(3,3)
print(X)
X[0]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2])

# Given the X numpy matrix, show the last row elements

In [117]:
X = np.arange(9).reshape(3,3)
print(X)
X[-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([6, 7, 8])

# Given the X numpy matrix, show the first element on first row

In [121]:
 X = np.arange(15).reshape(5,3)
print(X)
X[0][0]
#X[0,0]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


0

# Given the X numpy matrix, show the last element on last row

In [123]:
X = np.arange(15).reshape(3,5)
print(X)
X[-1,-1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


14

# Given the X numpy matrix, show the middle row elements

In [130]:
X = np.arange(15).reshape(3,5)
print(X)
X[1:-1, :]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[5, 6, 7, 8, 9]])

# Given the X numpy matrix, show the first two elements on the first three rows

In [138]:
X = np.arange(15).reshape(5,3)
print(X)
X[:3,:2]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[0, 1],
       [3, 4],
       [6, 7]])

# Given the X numpy matrix, show the last two elements on the last two rows

In [172]:
X = np.arange(30).reshape(6,5)
print(X)
X[-2:,-2:]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


array([[23, 24],
       [28, 29]])

# Array manipulation

# Convert the given integer numpy array to float

In [152]:
X = np.array([-2,-5.0,6,8,9])
np.array(X, np.float32)


array([-2., -5.,  6.,  8.,  9.], dtype=float32)

# Reverse the given numpy array (first element becomes last)

In [154]:
X = np.array([2,8,6,5,8,1])
X[::-1]

array([1, 8, 5, 6, 8, 2])

# Order (sort) the given numpy array

In [158]:
X = np.array([2,8,6,5,8,1])
X.sort()
X

array([1, 2, 5, 6, 8, 8])

# Given the X numpy array, set the fifth element equal to 1

In [159]:
X =  np.array([2,8,6,5,8,1])
X[4] = 1
X

array([2, 8, 6, 5, 1, 1])

# Given the X numpy array, change the 50 with a 40

In [162]:
X = np.arange(35, 50)
X
X[14] = 40
X

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 40])

# Given the X numpy matrix, change the last row with all 1

In [174]:
X = np.arange(24).reshape(6,4)
X[-1:][-1:] = 1
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 1,  1,  1,  1]])

# Given the X numpy matrix, change the last item on the last row with a 0

In [176]:
X = np.arange(30).reshape(6,5)
X[-1:, -1]=0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28,  0]])

# Given the X numpy matrix, add 5 to every element

In [182]:
X = np.array([[2,2],[1,5],[3,8]])
X+5

array([[ 7,  7],
       [ 6, 10],
       [ 8, 13]])

# Boolean arrays (also called masks)
### Given the X numpy array, make a mask showing negative elements

In [183]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

# Given the X numpy array, get numbers higher than 5

In [184]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X >= 5
mask

array([False, False, False, False,  True,  True, False, False, False,
        True])

# Given the X numpy array, get numbers higher than the elements mean

In [186]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X >= X.mean()
mask

array([False,  True, False, False,  True,  True, False, False, False,
        True])

# Given the X numpy array, get numbers equal to 2 or 10

In [188]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = (X == 2) | (X == 10)
mask

array([False,  True, False, False, False, False, False, False, False,
        True])

# Logic functions
### Given the X numpy array, return True if none of its elements is zero

In [192]:
X = np.array([-1,2,-4,0,0,5,6,-9,10])
X.all()

False

# Given the X numpy array, return True if any of its elements is zero

In [193]:
X = np.array([-1,2,-4,0,0,5,6,-9,10])
X.any()

True

# Summary statistics
### Given the X numpy array, show the sum of its elements

In [194]:
X = np.array([-1,2,-4,0,0,5,6,-9,10])
X.sum()

9

# Given the X numpy array, show the mean value of its elements

In [196]:
X = np.array([-1,2,-4,0,0,5,6,-9,10])
X.mean()

1.0

# Given the X numpy matrix, show the sum of its columns
##### remember: axis=0 columns; axis=1 rows

In [197]:
X = np.array([
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)  # remember: axis=0 columns; axis=1 rows

array([27, 30, 33, 36])

# Given the X numpy matrix, show the mean value of its rows
##### remember: axis=0 columns; axis=1 rows

In [198]:
X = np.array([
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=1)  # remember: axis=0 columns; axis=1 rows

array([26, 42, 58])

# Given the X numpy array, show the max value of its elements

In [200]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 15])

X.max()

15